spring.application.name=filevault-devlab
server.port=4040


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/filevault_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB


filevault.storage.location=D:/filevault/uploads

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs